spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 321321321

mybatis:
  configuration:
    map-underscore-to-camel-case: true #底線命名to駝峰命名

CLOUDINARY_URL: cloudinary://449757555464192:ZUkdSt1y8lBldqJZEkeUIzNlrE4@dsfmt4qaq